apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-frontend
  template:
    metadata:
      labels:
        app: loan-frontend
    spec:
      containers:
      - name: loan-frontend
        image: megazina/loan-frontend:latest
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: loan-frontend-service
spec:
  selector:
    app: loan-frontend
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
